<template
	><v-card>
		<v-card-title>
			Events
			<v-spacer></v-spacer>
			<v-text-field v-model="search" append-icon="mdi-magnify" label="Search" single-line hide-details></v-text-field>
		</v-card-title>
		<v-data-table
			:headers="headers"
			:items="events"
			:search="search"
			:items-per-page="15"
			:sort-by="['ID']"
			:sort-desc="[true]"
			:footer-props="{
				'disable-items-per-page': true,
			}"
		>
			<template v-slot:item.action="{ item }">
				<v-btn icon :to="'/statistics/events/' + item.ID"><v-icon>mdi-magnify</v-icon></v-btn>
			</template>
		</v-data-table>
	</v-card>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
@Component
export default class EventTable extends Vue {
	public headers = [
		{ text: "ID", value: "ID" },
		{
			text: "Name",
			align: "start",
			sortable: false,
			value: "name",
		},
		{ text: "Author", value: "author" },
		{ text: "Map", value: "map" },
		{ text: "Type", value: "type" },
		{ text: "Date", value: "date" },
		{ text: "Action", value: "action" },
	];
	public events = [
		{
			ID: 1,
			name: "Layo",
			author: "Theressa Norcop",
			type: "9-5",
			date: "6/2/2019",
		},
		{
			ID: 2,
			name: "Voomm",
			author: "Sofie Reichartz",
			type: "Focus",
			date: "9/21/2019",
		},
		{
			ID: 3,
			name: "Kanoodle",
			author: "Huberto Wabersinke",
			type: "Frontier",
			date: "4/20/2020",
		},
		{
			ID: 4,
			name: "Roodel",
			author: "Lazare Jeduch",
			type: "M5",
			date: "5/29/2019",
		},
		{
			ID: 5,
			name: "Avamba",
			author: "Lenci Alvaro",
			type: "V8",
			date: "5/11/2019",
		},
		{
			ID: 6,
			name: "Einti",
			author: "Celia Ruppeli",
			type: "Mighty Max Macro",
			date: "2/7/2020",
		},
		{
			ID: 7,
			name: "Topiclounge",
			author: "Tallie Huitt",
			type: "Sienna",
			date: "1/4/2020",
		},
		{
			ID: 8,
			name: "Feedbug",
			author: "Nelson Winkle",
			type: "riolet",
			date: "5/27/2019",
		},
		{
			ID: 9,
			name: "Eamia",
			author: "Danice Heymes",
			type: "Swift",
			date: "8/27/2019",
		},
		{
			ID: 10,
			name: "Centidel",
			author: "Pippa Clissett",
			type: "Element",
			date: "6/23/2019",
		},
		{
			ID: 11,
			name: "Aibox",
			author: "Cathee De Benedetti",
			type: "Sportvan G30",
			date: "9/15/2019",
		},
		{
			ID: 12,
			name: "Wordtune",
			author: "Barby Goolden",
			type: "MDX",
			date: "2/16/2020",
		},
		{
			ID: 13,
			name: "Edgeify",
			author: "Sibilla Backshell",
			type: "PT Cruiser",
			date: "11/26/2019",
		},
		{
			ID: 14,
			name: "Thoughtstorm",
			author: "Katrine Shepstone",
			type: "929",
			date: "6/8/2019",
		},
		{
			ID: 15,
			name: "Shuffledrive",
			author: "Goldy Kendal",
			type: "Econoline E150",
			date: "9/20/2019",
		},
		{
			ID: 16,
			name: "Feedfish",
			author: "Gage Maides",
			type: "Verano",
			date: "4/29/2019",
		},
		{
			ID: 17,
			name: "Gabspot",
			author: "Aymer Jandak",
			type: "Traverse",
			date: "2/19/2020",
		},
		{
			ID: 18,
			name: "Dynabox",
			author: "Derrek Felkin",
			type: "Mazda5",
			date: "3/7/2020",
		},
		{
			ID: 19,
			name: "Buzzbean",
			author: "Huntlee Sammut",
			type: "Savana 3500",
			date: "10/17/2019",
		},
		{
			ID: 20,
			name: "Voonte",
			author: "Lynnelle Duly",
			type: "Firebird",
			date: "2/16/2020",
		},
		{
			ID: 21,
			name: "Ainyx",
			author: "Bronson Baly",
			type: "CC",
			date: "11/30/2019",
		},
		{
			ID: 22,
			name: "Skipfire",
			author: "Allene Cowely",
			type: "Spectra",
			date: "2/4/2020",
		},
		{
			ID: 23,
			name: "Twimm",
			author: "Raeann Albery",
			type: "S10",
			date: "9/13/2019",
		},
		{
			ID: 24,
			name: "Realcube",
			author: "Paton Lubeck",
			type: "Lanos",
			date: "6/9/2019",
		},
		{
			ID: 25,
			name: "Kimia",
			author: "Raphael Buard",
			type: "240SX",
			date: "12/10/2019",
		},
		{
			ID: 26,
			name: "Photofeed",
			author: "Karil Malthus",
			type: "Storm",
			date: "8/28/2019",
		},
		{
			ID: 27,
			name: "Aibox",
			author: "Paulie Hague",
			type: "S-Class",
			date: "10/18/2019",
		},
		{
			ID: 28,
			name: "Meedoo",
			author: "Shea Bescoby",
			type: "C30",
			date: "9/21/2019",
		},
		{
			ID: 29,
			name: "Brainsphere",
			author: "Carl Domico",
			type: "F150",
			date: "5/22/2019",
		},
		{
			ID: 30,
			name: "Zoombox",
			author: "Aland Nekrews",
			type: "F150",
			date: "11/18/2019",
		},
		{
			ID: 31,
			name: "Realbridge",
			author: "Dilan McGiff",
			type: "Town & Country",
			date: "2/24/2020",
		},
		{
			ID: 32,
			name: "Quinu",
			author: "Sully Seward",
			type: "Leganza",
			date: "4/20/2019",
		},
		{
			ID: 33,
			name: "Divanoodle",
			author: "Filide Adie",
			type: "MX-6",
			date: "4/22/2020",
		},
		{
			ID: 34,
			name: "Quinu",
			author: "Gordie Gall",
			type: "1500 Club Coupe",
			date: "7/19/2019",
		},
		{
			ID: 35,
			name: "Yabox",
			author: "Ruby Clucas",
			type: "RL",
			date: "4/1/2020",
		},
		{
			ID: 36,
			name: "Myworks",
			author: "Daryl Izard",
			type: "2500",
			date: "4/7/2020",
		},
		{
			ID: 37,
			name: "Photofeed",
			author: "Gottfried Eddins",
			type: "TL",
			date: "1/18/2020",
		},
		{
			ID: 38,
			name: "Innojam",
			author: "Meridel Nezey",
			type: "Paseo",
			date: "6/22/2019",
		},
		{
			ID: 39,
			name: "Jaxworks",
			author: "Bobbie Eyes",
			type: "Santa Fe",
			date: "3/14/2020",
		},
		{
			ID: 40,
			name: "Voonix",
			author: "Kalie Ickeringill",
			type: "Prizm",
			date: "3/15/2020",
		},
		{
			ID: 41,
			name: "Roomm",
			author: "Anstice Gristock",
			type: "E-Class",
			date: "9/29/2019",
		},
		{
			ID: 42,
			name: "Babbleset",
			author: "Simona Rosier",
			type: "Crossfire",
			date: "3/10/2020",
		},
		{
			ID: 43,
			name: "Topicshots",
			author: "Grannie Colegrove",
			type: "SX4",
			date: "4/16/2020",
		},
		{
			ID: 44,
			name: "Kwideo",
			author: "Linnie Frays",
			type: "350Z",
			date: "9/21/2019",
		},
		{
			ID: 45,
			name: "Topdrive",
			author: "Constantin Starsmore",
			type: "Wrangler",
			date: "8/22/2019",
		},
		{
			ID: 46,
			name: "Flashspan",
			author: "Garold Breckwell",
			type: "Cobalt",
			date: "2/29/2020",
		},
		{
			ID: 47,
			name: "Skiba",
			author: "Kayle Westwick",
			type: "80",
			date: "2/16/2020",
		},
		{
			ID: 48,
			name: "Twitterbeat",
			author: "Joseito de Vaen",
			type: "E250",
			date: "7/31/2019",
		},
		{
			ID: 49,
			name: "Avamm",
			author: "Winona Turton",
			type: "Versa",
			date: "11/27/2019",
		},
		{
			ID: 50,
			name: "Kwilith",
			author: "Siobhan Condie",
			type: "IS-F",
			date: "11/14/2019",
		},
		{
			ID: 51,
			name: "Topicblab",
			author: "Adolphe Amorine",
			type: "TL",
			date: "11/21/2019",
		},
		{
			ID: 52,
			name: "Youbridge",
			author: "Randie Brignall",
			type: "Pathfinder",
			date: "4/6/2020",
		},
		{
			ID: 53,
			name: "Mymm",
			author: "Betsey Debrick",
			type: "Taurus",
			date: "6/23/2019",
		},
		{
			ID: 54,
			name: "Gigazoom",
			author: "Olivero Gribbon",
			type: "Tercel",
			date: "3/13/2020",
		},
		{
			ID: 55,
			name: "Livetube",
			author: "Judy Just",
			type: "Grand Prix",
			date: "9/8/2019",
		},
		{
			ID: 56,
			name: "Lazzy",
			author: "Jerrie Lacelett",
			type: "Focus",
			date: "5/2/2019",
		},
		{
			ID: 57,
			name: "Eabox",
			author: "Keven Cooch",
			type: "Cobalt",
			date: "5/26/2019",
		},
		{
			ID: 58,
			name: "Gabvine",
			author: "Evin Bonafant",
			type: "Tahoe",
			date: "12/9/2019",
		},
		{
			ID: 59,
			name: "Thoughtbeat",
			author: "Elnora Dicker",
			type: "S8",
			date: "9/13/2019",
		},
		{
			ID: 60,
			name: "Fivespan",
			author: "Mikel St. Quentin",
			type: "A5",
			date: "4/17/2019",
		},
		{
			ID: 61,
			name: "Babbleblab",
			author: "Lotta Klaves",
			type: "Continental GTC",
			date: "2/11/2020",
		},
		{
			ID: 62,
			name: "Fivebridge",
			author: "Brenda Kleehuhler",
			type: "Volt",
			date: "5/2/2019",
		},
		{
			ID: 63,
			name: "Kazio",
			author: "Rozelle Spaxman",
			type: "Reatta",
			date: "8/4/2019",
		},
		{
			ID: 64,
			name: "Jamia",
			author: "Ikey Fannin",
			type: "Ram 1500",
			date: "8/12/2019",
		},
		{
			ID: 65,
			name: "Zoonoodle",
			author: "Reynolds Monget",
			type: "Firefly",
			date: "1/26/2020",
		},
		{
			ID: 66,
			name: "Blogtag",
			author: "Merwyn Gamblin",
			type: "Equator",
			date: "10/23/2019",
		},
		{
			ID: 67,
			name: "Lajo",
			author: "Trent Bramsen",
			type: "SL-Class",
			date: "5/17/2019",
		},
		{
			ID: 68,
			name: "Eare",
			author: "Bernard Buesden",
			type: "Rodeo",
			date: "7/31/2019",
		},
		{
			ID: 69,
			name: "Voolia",
			author: "Sarina Silversmid",
			type: "Canyon",
			date: "6/18/2019",
		},
		{
			ID: 70,
			name: "Gigabox",
			author: "Brewster Fuzzens",
			type: "6 Series",
			date: "9/1/2019",
		},
		{
			ID: 71,
			name: "Gigashots",
			author: "Jeremiah Meaddowcroft",
			type: "900",
			date: "9/23/2019",
		},
		{
			ID: 72,
			name: "Skyba",
			author: "Tish Gillis",
			type: "Elise",
			date: "2/12/2020",
		},
		{
			ID: 73,
			name: "Buzzdog",
			author: "Toddy Dyton",
			type: "Freelander",
			date: "3/24/2020",
		},
		{
			ID: 74,
			name: "Oyoba",
			author: "Kristian Yurchenko",
			type: "Corvette",
			date: "11/26/2019",
		},
		{
			ID: 75,
			name: "Skinte",
			author: "Malissa Gantz",
			type: "Acadia",
			date: "3/4/2020",
		},
		{
			ID: 76,
			name: "Oodoo",
			author: "Andrej Tratton",
			type: "M3",
			date: "8/17/2019",
		},
		{
			ID: 77,
			name: "Trudoo",
			author: "Field Sterrie",
			type: "6000",
			date: "10/26/2019",
		},
		{
			ID: 78,
			name: "Tazzy",
			author: "Emmery Brookshaw",
			type: "Park Avenue",
			date: "12/26/2019",
		},
		{
			ID: 79,
			name: "Rhycero",
			author: "Frazier Balham",
			type: "QX",
			date: "12/22/2019",
		},
		{
			ID: 80,
			name: "Zoombeat",
			author: "Eleen Diggons",
			type: "New Beetle",
			date: "9/29/2019",
		},
		{
			ID: 81,
			name: "Twitterlist",
			author: "Jeffrey Deave",
			type: "Sentra",
			date: "10/13/2019",
		},
		{
			ID: 82,
			name: "Dynava",
			author: "Fran Sans",
			type: "Quattroporte",
			date: "6/21/2019",
		},
		{
			ID: 83,
			name: "Wikizz",
			author: "Fredek Tuiller",
			type: "V8",
			date: "6/23/2019",
		},
		{
			ID: 84,
			name: "JumpXS",
			author: "Fern Fairholme",
			type: "G",
			date: "7/30/2019",
		},
		{
			ID: 85,
			name: "Browsebug",
			author: "Renie Sugden",
			type: "4Runner",
			date: "1/1/2020",
		},
		{
			ID: 86,
			name: "Latz",
			author: "Owen Brizland",
			type: "G25",
			date: "10/30/2019",
		},
		{
			ID: 87,
			name: "Avamba",
			author: "Georgianna Cassells",
			type: "Rio",
			date: "4/12/2019",
		},
		{
			ID: 88,
			name: "Aivee",
			author: "Fields Dolligon",
			type: "Vandura G3500",
			date: "12/2/2019",
		},
		{
			ID: 89,
			name: "Lazz",
			author: "Alisander Kliemke",
			type: "Integra",
			date: "4/22/2019",
		},
		{
			ID: 90,
			name: "Lazz",
			author: "Zarah O'Hartagan",
			type: "Custom Cruiser",
			date: "9/3/2019",
		},
		{
			ID: 91,
			name: "Fliptune",
			author: "Sophia McGrann",
			type: "QX56",
			date: "3/29/2020",
		},
		{
			ID: 92,
			name: "Wikizz",
			author: "Drucill Emslie",
			type: "E-Series",
			date: "4/9/2019",
		},
		{
			ID: 93,
			name: "Voolith",
			author: "Allister MacAlpyne",
			type: "Sunbird",
			date: "4/20/2019",
		},
		{
			ID: 94,
			name: "Talane",
			author: "Gilbertine Crallan",
			type: "MPV",
			date: "5/25/2019",
		},
		{
			ID: 95,
			name: "Bluejam",
			author: "Daryle Hutable",
			type: "Montego",
			date: "7/1/2019",
		},
		{
			ID: 96,
			name: "Devshare",
			author: "Linda Neumann",
			type: "Sonata",
			date: "5/30/2019",
		},
		{
			ID: 97,
			name: "Shuffletag",
			author: "Aylmar Voas",
			type: "9-3",
			date: "4/9/2020",
		},
		{
			ID: 98,
			name: "Digitube",
			author: "Gery Beininck",
			type: "Grand Vitara",
			date: "1/1/2020",
		},
		{
			ID: 99,
			name: "Youopia",
			author: "Virgil Pickless",
			type: "Firebird",
			date: "8/22/2019",
		},
		{
			ID: 100,
			name: "Eare",
			author: "Mahala Dust",
			type: "Savana",
			date: "9/11/2019",
		},
	];
	public search = "";
}
</script>

<style scoped></style>
